services:
  - type: web
    name: safety-insight-flask
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DATABASE_URL
        fromDatabase:
          name: safety-insight-postgres
          property: connectionString

databases:
  - name: safety-insight-postgres
